[project]
name = "recap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ruff>=0.15.0",
]

[project.scripts]
recap = "main:main"

[tool.ruff]
line-length = 100
